#
# Copyright (c) 2020, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
#

ARG sdk_vsn=1.6.0

FROM digitalasset/daml-sdk:${sdk_vsn}

WORKDIR /home/daml

COPY target/know-your-customer.dar /home/daml/

USER root
RUN chown daml know-your-customer.dar
USER daml

EXPOSE 6865

CMD ~/.daml/bin/daml sandbox -- --wall-clock-time --address 0.0.0.0 --port 6865 know-your-customer.dar
